name: Export

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Upload jar file
        uses: actions/upload-artifact@v4
        with:
          name: data.json
          path: data/data.json