name: Run

on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 525600
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 20
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run
        run: gradle run